# Define a global platform for your project
platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# Define the project settings
project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

# Required for Flutter CocoaPods integration
require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  # Add target for tests (if applicable)
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

# Post-installation script to fix base configuration issue
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    # Set the Base Configuration for Debug, Profile, and Release
    target.build_configurations.each do |config|
      if config.name == 'Debug'
        config.base_configuration_reference = installer.pods_project.files.find { |f| f.path == 'Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig' }
      elsif config.name == 'Profile'
        config.base_configuration_reference = installer.pods_project.files.find { |f| f.path == 'Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig' }
      elsif config.name == 'Release'
        config.base_configuration_reference = installer.pods_project.files.find { |f| f.path == 'Target Support Files/Pods-Runner/Pods-Runner.release.xcconfig' }
      end
    end
  end
end
